sonata_admin:
    title: 'Pornic'
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css
    
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
