sonata_admin:
    title: 'Pornic'
    # templates:
    #     layout: 'Admin/standard_layout.html.twig'
        
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
