twig:
  default_path: '%kernel.project_dir%/templates'
  paths:
    '%kernel.project_dir%/public': public_path
    '%kernel.project_dir%/templates/bundles': sonataBundles
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  form_themes:
    - '@sonataBundles/mediaPreview.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - '@SonataCore/Form/datepicker.html.twig'